---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3gallery
spec:
  selector:
    matchLabels:
      app: s3gallery
  replicas: 1
  template:
    metadata:
      labels:
        app: s3gallery
    spec:
      containers:
        - name: s3gallery
          image: sunua/gh-s3gallery:prod
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_PASSWORD
            - name: DB_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DB_CONN_STR
            - name: AWS_SECRET_ACCESS_KEY
              value: "RDH7h1koFYSL9u6eF0O9gj6DWhO4C8L5"
            - name: AWS_ACCESS_KEY_ID
              value: "go72hFzS8OE085Sb22cxDXkf4QCeXsu4"


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3gallery
  name: s3gallery
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: s3gallery