name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            sunua/gh-s3gallery:latest
          # build on feature branches, push only on main branch
          push: ${{ true }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_on_cluster:
    name: Deploy on k8s cluster
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG}} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
#          context: <context name>  #If left unspecified, current-context from kubeconfig is used as default
        id: setcontext
      - uses: Azure/k8s-deploy@v3.1
        with:
          manifests: |
            s3gallery_deploy.yaml
          images: 'sunua/gh-s3gallery:latest'
